import Mathlib

-- CONSTANTS -----------------------------
def ShimCount : ℕ := 2
def DataCount : ℕ := 4
def NetMax : ℕ := 10
def AddrCount : ℕ := 2
def MaxTimestamp : ℕ := 100
def InstrCount : ℕ := 2


-- TYPES -----------------------------------------
def ShimId : Type := {i : Fin (ShimCount + 1) // i.val ≠ 0 }
def Addr : Type := Fin AddrCount
def Data : Type := Fin (DataCount + 1)
def Timestamp : Type := Fin (MaxTimestamp + 1)
def Node : Type := Fin (ShimCount + 1)
-- ShimId: 1..ShimCount;       	-- For indexing into list of shims
-- Addr: 0..AddrCount-1;		      -- For indexing into cache
-- Data: 0..DataCount;
-- Timestamp: 0..MaxTimestamp;
-- Node: 0..ShimCount;         	-- This represents the CC plus the shims: CC = 0, Shims = 1..ShimCount+1

inductive MType : Type where
    | WRITE
    | WRITE_ACK
    | RREQ
    | EVICT
    | FREQ
    | RRESP
    | FRESP

inductive OpStrength : Type where
    | RLX
    | REL
    | ACQ
    | SC

structure Message : Type where
    mtype : MType
    src : Node
    dst : Node
    data : Data
    addr : Addr
    ts : Timestamp
    stren : OpStrength

-- matrix one row of messages per node (CC + shims)
def NETOrdered : Type := Matrix Node (Fin (NetMax)) Message
def NETOrderedCount : Type := Vector ℕ (ShimCount + 1)
-- NETOrdered: array[Node] of array[0..NetMax-1] of Message;
-- NETOrderedCount: array[Node] of 0..NetMax;
-- NETUnordered: array[Node] of multiset[NetMax] of Message;

inductive CacheState : Type where
    | Invalid | Valid

structure ShimElemState : Type where
    state : CacheState
    data : Data
    ts : Timestamp
    syncBit : Bool

structure CCElemState : Type where
    data : Data
    ts : Timestamp
    sharers : Vector Bool ShimCount

def ShimCache : Type := Vector ShimElemState AddrCount
def CCCache : Type := Vector CCElemState AddrCount

-- Litmus test specific---------
inductive PermissionType : Type where
    | load
    | store
    | fence
    | none

structure Instr : Type where
    access : PermissionType       -- may not need this
    stren : OpStrength
    addr : Addr
    data : Data      -- Value store for read operation performed */
    pend : Bool


structure FifoQueue : Type where                      -- each shim has a queue of litmust test instructions to perform
    Queue: Vector Instr InstrCount -- array[0..2] of Instr;
    QueueInd: Fin (InstrCount + 2) -- 0..2+1;
    QueueCnt: Fin (InstrCount + 2) -- 0..2+1;

---------------------------------
structure Shim : Type where
    state : ShimCache
    active : Bool   -- active = still needs to execute litmus tests instructions
    pendingWSC : Bool
    fencePending : Bool
    queue : FifoQueue   -- queue of litmus test instructions to be performed


structure CCMachine : Type where
    cache : CCCache
    queue : FifoQueue

-- NOTE: this is zero indexed unlike in murphi model....... change?
def ShimType : Type := Vector Shim ShimCount    -- array[ShimId] of Shim;



----------------------------------------------------------------------
-- Variables
----------------------------------------------------------------------
-- def CC : CCMachine := sorry
-- def Shims : ShimType := sorry       -- Q: queues for each shim are instructions for litmus tests or local reads/writes. Net is 2d array, storing non-local writes from the CC?
-- def Net : NETOrdered := sorry
-- def NetCount : NETOrderedCount := sorry





-- inductive Op where
--     | read (addr : Nat)
--     | write (addr : Nat) (val : Nat)
--     | noop
--     deriving Inhabited, Repr

-- structure Instr : Type where
--     access : PermissionType       -- may not need this
--     stren : OpStrength
--     addr : Addr
--     data : Data      -- Value store for read operation performed */
--     pend : Bool

universe u
set_option diagnostics true
-- A single trace is a sequence of operations.
def Trace (α : Type u) (steps : Nat) := Fin steps → α
#check Trace Instr 2
def sometrace : Trace Instr 2 :=
  ![
    { access := PermissionType.load, stren := OpStrength.RLX, addr := ⟨0, by decide⟩, data := ⟨0, by decide⟩, pend := false },
    { access := PermissionType.store, stren := OpStrength.SC, addr := ⟨1, by decide⟩, data := ⟨1, by decide⟩, pend := true }
  ]
#check sometrace 0

-- Multi-threaded traces are a sequence of traces.
def TraceSet (α : Type u) (threads : Nat) (steps : Nat) := Fin threads → Trace α steps
#check TraceSet Instr 3 2

-- The execution trace generated by the program.
def Execution (threads steps : Nat) := TraceSet Instr threads steps
#check Execution 3 2
-- The output trace generated by the cache coherence protocol.
def Output (threads steps : Nat) := TraceSet (Option Nat) threads steps
#check Output 3 2

/--
1. Writes to the same address are totally ordered.
2. Reads return the most recent write in that order.
3. Writes become visible to all processors atomically.
-/
structure Coherence {threads steps steps' : Nat} (e : Execution threads steps) (o : Output threads steps') : Prop where
    writes_total_order : False -- Placeholder for actual definition
    -- ∀ writes w1, w2. ((∀ threads w1 < w2) or (∀ threads w1 > w2))??
    reads_return_last_write : False -- Placeholder for actual definition
    write_atomicity : False -- Placeholder for actual definition


def protocol {threads steps steps' : Nat} (e : Execution threads steps) : (Output threads steps') :=
    sorry -- Implementation of the protocol goes here

theorem protocol_respects_coherence :
    ∀ {threads steps steps' : Nat} (e : Execution threads steps) (o : Output threads steps'), protocol e = o → Coherence e o := by sorry


----------------------------------------------------------------------
-- Procedures
----------------------------------------------------------------------
