name = "memglue_verification"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["MemglueVerification"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "af84080c8101dd6edcbf19073b38f926f4cd2b35"

[[lean_lib]]
name = "MemglueVerification"
